from .config import AnalyseConfig
from .core import analyse as _analyse


def analyse(
    input: str,
    grid: float = 0.01,
    probe: float = 0.0,
    atoms: str | None = None,
    threads: int = 0,
    out_prefix: str | None = None,
    no_surface: bool = False,
    pore: bool = False,
    porevis: bool = False,
    no_octree: bool = False,
    oct_level: int = 2,
    oct_grid: float = 0.001,
    cube: bool = False,
    cube_space: float | None = None,
    smooth: bool = False,
    stats: bool = False,
    debug: bool = False,
    debug_print: bool = False,
    connectivity: str = "legacy",
    transport_direction: str = "any",
    psd_method: str = "mc",
    psd_mc_samples: int = 50000,
    psd_mc_seed: int = 11451466,
    psd_mc_bin_size: float | None = None,
    surface_samples: int = 1000,
    psd_local_max_mode: str = "strict",
    psd_min_center_radius: float = 0.005,
    psd_overlap_prune: bool = True,
    psd_overlap_threshold: float = 1.0,
    psd_hist_weighting: str = "volume",
    psd_center_bin_size: float | None = None,
    psd_mc_search: str = "pyramid",
):
    cfg = AnalyseConfig(
        input=input,
        grid=grid,
        probe=probe,
        connectivity=connectivity,
        transport_direction=transport_direction,
        psd_method=psd_method,
        psd_mc_samples=psd_mc_samples,
        psd_mc_seed=psd_mc_seed,
        psd_mc_bin_size=psd_mc_bin_size,
        surface_samples=surface_samples,
        psd_local_max_mode=psd_local_max_mode,
        psd_min_center_radius=psd_min_center_radius,
        psd_overlap_prune=psd_overlap_prune,
        psd_overlap_threshold=psd_overlap_threshold,
        psd_hist_weighting=psd_hist_weighting,
        psd_center_bin_size=psd_center_bin_size,
        psd_mc_search=psd_mc_search,
        atoms=atoms,
        threads=threads,
        out_prefix=out_prefix,
        no_surface=no_surface,
        pore=pore,
        porevis=porevis,
        no_octree=no_octree,
        oct_level=oct_level,
        oct_grid=oct_grid,
        cube=cube,
        cube_space=cube_space,
        smooth=smooth,
        stats=stats,
        debug=debug,
        debug_print=debug_print,
    )
    return _analyse(cfg)
